version: '3.3'

services:
  php-fpm:
    build: ./
    ports:
      - 5000:8000
    volumes:
      - ./:/var/www/html
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8181:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
  elasticsearch:
      build:
        context: elasticsearch/
        args:
          ELK_VERSION: $ELK_VERSION
      volumes:
        - type: bind
          source: "./elasticsearch/config/elasticsearch.yml"
          target: "/usr/share/elasticsearch/config/elasticsearch.yml"
          read_only: true
        - type: volume
          source: elasticsearch
          target: /usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        ELASTIC_PASSWORD: changeme
        discovery.type: single-node
      networks:
        - elk
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: "./logstash/config/logstash.yml"
        target: "/usr/share/logstash/config/logstash.yml"
        read_only: true
      - type: bind
        source: "./logstash/pipeline"
        target: "/usr/share/logstash/pipeline"
        read_only: true
    ports:
      - "5100:5100"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: "./kibana/config/kibana.yml"
        target: "/usr/share/kibana/config/kibana.yml"
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
volumes:
  elasticsearch: